version: '3.8'

services:
  multicurrecncywalletapp:
    #    image: 'multicurrencyapp'
    build:
      context: .
    restart: on-failure
    container_name: multicurrecncywalletapp
    ports:
      - 9000:9000
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/wallet_app?createDatabaseIfNotExist=true
      SPRING_PROFILE_ACTIVE: docker
      MYSQL_PASSWORD: admin
      MYSQL_DB_NAME: wallet_app
      MYSQL_HOSTNAME: mysqldb
      MYSQL_PORT: 3309
      MYSQL_USERNAME: root


  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wallet_app
      MYSQL_ROOT_PASSWORD: admin
